import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";


export const metadata: Metadata = {
  title: "نرم افزار TaskBoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
      <ToastContainer position="top-center" autoClose={3000} rtl={true} />
        {children}
      </body>
    </html>
  );
}
